import { llmVision, downloadAsDataUri } from "./fal.mjs";

const IMPLEMENTER_SYSTEM = `You are a staff-level front-end engineer + designer. You receive a tall desktop website mockup image (generated by gpt-image-2) that represents the FINAL intended design of a site, and a BRIEF that gives you the actual brand copy.

Your job: write a SINGLE complete index.html that reproduces the mockup as faithfully as possible: same sections, same order, same layout, same typography feel, same palette, same copy (verbatim from the brief), same tone. The HTML is the implementation; the mockup is the spec.

Hard requirements:
- Output ONLY the HTML. No markdown fences, no commentary, no preamble.
- Self-contained single <!doctype html> document.
- Tailwind CSS via CDN: <script src="https://cdn.tailwindcss.com"></script>.
- Google Fonts via <link>: pick fonts that visually match the mockup (do not default to Inter).
- Inline <style> for custom spacing, motion, or details that Tailwind utilities don't cover.
- Minimal vanilla JS only if truly needed.
- Fully responsive, mobile-first, polished at every breakpoint.
- Accessible: semantic HTML, alt text, aria-labels, contrast.
- Use ONLY copy from the brief (tagline, sections, CTAs). You may tighten phrasing.
- Include a proper <nav>, hero section, all body sections shown in the mockup, and a footer.
- The hero <img> MUST use src="{{HERO_IMAGE}}" (the mockup image itself will be swapped in as the hero / backdrop).
- Match the mockup's palette precisely: pull hex-adjacent colors from what you see.
- Match the mockup's typography feel precisely: serif/sans mix, display weight, tracking.
- Tasteful motion: CSS transitions on hover/focus, subtle keyframes where fitting.

Absolute rule: what you ship must look like a real, production-ready version of the mockup: not a generic landing page. Think design-award Site-of-the-Day quality.`;

export async function implementFromMockup({ brief, direction, mockupUrl }) {
  const prompt = [
    `BRIEF:`,
    JSON.stringify(brief, null, 2),
    ``,
    `DESIGN DIRECTION: ${direction.label}: ${direction.vibe}`,
    ``,
    `The attached image IS the approved design spec for this site. Reproduce it in a single-file index.html now. Remember: hero <img> src="{{HERO_IMAGE}}".`,
  ].join("\n");

  const html = await llmVision({
    system_prompt: IMPLEMENTER_SYSTEM,
    prompt,
    image_urls: [mockupUrl],
    temperature: 0.6,
    max_tokens: 16_000,
    model: "anthropic/claude-sonnet-4.6",
  });

  return cleanupHtml(html);
}

export async function mockupToDataUri(url) {
  return await downloadAsDataUri(url);
}

function cleanupHtml(text) {
  let t = text.trim().replace(/^```(?:html)?\s*/i, "").replace(/```\s*$/, "").trim();
  const i = t.search(/<!doctype html>/i);
  if (i > 0) t = t.slice(i);
  // Strip anything after the closing </html>: opus sometimes appends a
  // leaked ```tiles code fence (or other commentary) past the document end,
  // which then renders as visible text in the browser. Truncate at </html>.
  const endMatch = t.match(/<\/html\s*>/i);
  if (endMatch && endMatch.index !== undefined) {
    t = t.slice(0, endMatch.index + endMatch[0].length);
  }
  if (!/<!doctype html>/i.test(t)) {
    throw new Error(`implementer did not return a full HTML document: ${t.slice(0, 200)}`);
  }
  return t;
}
